# Generated by Django 4.2.4 on 2023-11-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_author_alter_postauthor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postauthor',
            options={'permissions': (('can_update', 'Update post content.'),)},
        ),
    ]
