# Generated by Django 4.2.4 on 2023-11-15 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_post_options_alter_postauthor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "permissions": (
                    ("creator", "Can create, update and delete creator content."),
                )
            },
        ),
    ]
