# Generated by Django 4.2.4 on 2023-12-18 20:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0010_alter_post_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PostAuthor",
            new_name="Author",
        ),
    ]
