# Generated by Django 5.2.4 on 2025-09-05 23:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_postcomment_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_posted',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='last_modified',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='last_modified',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
